AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  test_api_gateway

  Sample SAM Template for test_api_gateway

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ServiceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: service/
      Handler: app.handler
      Runtime: python3.8
      Events:
        Read:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: GET
          Auth:
            UsagePlan:
              CreateUsagePlan: SHARED
            ApiKeyRequired: true
          RequestParameters:
            - method.request.header.Authorization:
                Required: true
          TracingEnabled: true
        Docs:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /docs
            Method: GET
          Auth:
            UsagePlan:
              CreateUsagePlan: SHARED
            ApiKeyRequired: false
          RequestParameters:
            - method.request.header.Authorization:
                Required: true
          TracingEnabled: true
        Create:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: POST
          Auth:
            UsagePlan:
              CreateUsagePlan: SHARED
            ApiKeyRequired: true
          RequestParameters:
            - method.request.header.Authorization:
                Required: true
          TracingEnabled: true

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CheckApi:
    Description: "API Gateway endpoint URL for Prod stage for Check function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ServiceFunction:
    Description: "Check Lambda Function ARN"
    Value: "ServiceFunction"
  ServiceFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt ServiceFunctionRole.Arn
